### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by jaylac2000** [xSoapers/AuctionHouseGUI#1]
Internal server error if ran in game: [Server thread/CRITICAL]: TypeError: "Argument 1 passed to xsoapers\AuctionHouseGUI\Task\AHWindow::__construct() must be an instance of xsoapers\AuctionHouseGU\Main, instance of xsoapers\AuctionHouseGUI\Main given, called in phar://C:/Users/Administrator/Documents/mc servers/TestSERVERS/test/plugins/AuctionHouseGUI_dev-1.phar/src/xsoapers/AuctionHouseGUI/Main.php on line 318" (EXCEPTION) in "plugins/AuctionHouseGUI_dev-1.phar/src/xsoapers/AuctionHouseGUI/Task/AHWindow" at line 16

Console: [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\command\ConsoleCommandSender::getLowerCaseName()" (EXCEPTION) in "plugins/AuctionHouseGUI_dev-1.phar/src/xsoapers/AuctionHouseGUI/Main" at line 858

If running from console it should say to run the command in game

**Comment by xSoapers** [comment]
use FormAPI 
https://poggit.pmmp.io/ci/jojoe77777/FormAPI/FormAPI

**Comment by xSoapers** [comment]
only work in game bruh

**Comment by jaylac2000** [comment]
Still, if ran from console it should say "in game only" or "in game command only" or "use in game" or something along them lines.. not crash the server (make the server restart
